const AUTH_STORAGE_KEY = 'wa_cert_authenticated';
const UPDATE_VIDEOS = 'UPDATE_VIDEOS';
const UPDATE_LOADING = 'UPDATE_LOADING';
const UPDATE_ERROR = 'UPDATE_ERROR';
const SELECT_VIDEO = 'SELECT_VIDEO';
const UPDATE_QUERY_VIDEO = 'UPDATE_QUERY_VIDEO';
const CHANGE_MODE="CHANGE_MODE";

export {
  AUTH_STORAGE_KEY,
  UPDATE_VIDEOS,
  UPDATE_LOADING,
  UPDATE_ERROR,
  SELECT_VIDEO,
  UPDATE_QUERY_VIDEO,
  CHANGE_MODE
};
